name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.2 # Use a newer version
        with:
          buildozer_version: latest # Corrected parameter name
          workdir: .
          command: buildozer -v android debug
