name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
        env:
          PIP_BREAK_SYSTEM_PACKAGES: "1"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SabianOracle
          path: ${{ steps.buildozer.outputs.filename }}
